kind: pipeline
name: anu anu anu anjay

steps:
- name: gaskan
  image: ubuntu:focal
  environment:
    URL: https://bigota.d.miui.com/V12.0.1.0.RCOCNXM/miui_GINKGO_V12.0.1.0.RCOCNXM_d885534244_11.0.zip
    ORIGIN:
      from_secret: ORIGIN
  commands:
  - apt update && apt install -qy git
  - git clone $ORIGIN gas
  - cd gas && rm -rf .git
  - bash gas.sh
