kind: pipeline
name: anu anu anu anjay

steps:
- name: gaskan
  image: ubuntu:focal
  environment:
    URL: http://bigota.d.miui.com/21.2.3/miui_GINKGO_21.2.3_99c99353ec_11.0.zip
    ORIGIN:
      from_secret: ORIGIN
  commands:
  - apt update && apt install -qy git
  - git clone $ORIGIN gas
  - cd gas && rm -rf .git
  - bash ./gas.sh
